version: "3"
services:
  app:
    container_name: animalsdb
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - /var/lib/mongodb:/data/db
    ports: 
      - "27017:27017"
